name: eng2indo
description: A dictionary app for English-Indonesian translations

# This version number can be changed at any time.
# It is a number that helps track different releases of the app.
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2  # Untuk melakukan HTTP request ke FastAPI
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


# sudah ter setting untuk flutter dan sdk nya

